apiVersion: v2
name: doccano
appVersion: 1.6.2
version: 2.0.2
description: A Helm chart for doccano, Open source text annotation tool for machine learning practitioner.
home: https://doccano.herokuapp.com/
icon: https://raw.githubusercontent.com/doccano/doccano/master/docs/images/logo/doccano.png
sources:
  - https://github.com/doccano/doccano
maintainers:
  - name: armandleopold
    email: armand.leopold@curie.fr
kubeVersion: ">= 1.14.0-0"
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.1.9
keywords:
  - annotation
  - ml
  - text
  - machine-learning
annotations:
  artifacthub.io/images: |
    - name: doccano
      image: doccano/doccano:1.6.2
