image:
  replicaCount: 1
  repository: doccano/doccano
  tag: "1.6.2"
  pullPolicy: IfNotPresent
  name: doccano
  deployRegistry: false
  imagePullSecrets: registrysecret
  dataSecret: |-
    {"auths":{"registry.localhost":{"password":"","username":""}}}

env:
  ADMIN_EMAIL: admin@localhost
  ADMIN_USERNAME: admin

deploySecret: true
ADMIN_PASSWORD: password

service:
  type: ClusterIP
  targetPort: 8000
  protocol: TCP

ingress:
  enabled: true
  path: /
  hostnames:
  - doccano.localhost
  tls:
  - hosts:
    - doccano.localhost
    secretName: doccano

persistence:
  enabled: true
  existingClaim: false
  size: 10Gi
  accessMode: "ReadWriteOnce"
  volumeName: "data"
  mountPath: /data

  annotations:
    helm.sh/resource-policy: keep

postgresql:
  global:
    postgresql:
      auth:
        database: doccano
        username: doccano
        password: 58sdf9hgd1gs8sdfzerJHFdf
