image:
  replicaCount: 1
  repository: ghcr.io/curie-data-factory/job-orchestrator
  tag: "1.3.3"
  pullPolicy: IfNotPresent
  name: job-orchestrator
  deployRegistry: false
  imagePullSecrets: registrysecret
  dataSecret: |-
    {"auths":{"registry.company.com":{"password":"","username":""}}}

service:
  type: ClusterIP
  targetPort: 80
  protocol: TCP

ingress:
  enabled: true
  hostnames:
  - job-orchestrator.company.com
  tls:
  - hosts:
    - job-orchestrator.company.com
    secretName: job-orchestrator

configMap:
  mountPath: /var/www/html/conf/
  data: |-
    ""

  cifs: |-
    ""

ldapConf:
  key: conf.php
  mountPath: /var/www/html/ldapconf/
  data: |-
    ""
